# Generated by Django 4.1.7 on 2023-04-12 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blobing', '0006_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Text limit of 8000 words', null=True),
        ),
    ]
